-- MySQL Script generated by MySQL Workbench
-- 05/22/19 22:26:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cursos_inter` DEFAULT CHARACTER SET utf8 ;
USE `Cursos_inter` ;

-- -----------------------------------------------------
-- Table `mydb`.`Registro_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursos_inter`.`Registro_user` (
  `Num_cuenta` INT UNSIGNED NOT NULL,
  `Nombre(s)` VARCHAR(45) NOT NULL,
  `Ap_pat` VARCHAR(15) NOT NULL,
  `Ap_mat` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`Num_cuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursos_inter`.`Cursos` (
  `idCursos` INT UNSIGNED NOT NULL,
  `Nombre_curso` VARCHAR(45) NOT NULL,
  `Carrera` VARCHAR(45) NOT NULL,
  `Cupo` TINYINT(2) UNSIGNED NOT NULL,
  `Salon` VARCHAR(6) NOT NULL,
  `Horario` DATETIME NOT NULL,
  PRIMARY KEY (`idCursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos_inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursos_inter`.`Cursos_inscritos` (
  `Registro_user_Num_cuenta` INT UNSIGNED NOT NULL,
  `Cursos_idCursos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Registro_user_Num_cuenta`, `Cursos_idCursos`),
  INDEX `fk_Registro_user_has_Cursos_Cursos1_idx` (`Cursos_idCursos` ASC),
  INDEX `fk_Registro_user_has_Cursos_Registro_user_idx` (`Registro_user_Num_cuenta` ASC),
  CONSTRAINT `fk_Registro_user_has_Cursos_Registro_user`
    FOREIGN KEY (`Registro_user_Num_cuenta`)
    REFERENCES `Cursos_inter`.`Registro_user` (`Num_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_user_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `Cursos_inter`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
